### ISSUE TITLE
py4j.protocol.py4jjavaerror 

### ISSUE THREAD

**Issue by shailvshah** [maxpumperla/elephas#117]
I'm trying to run this on Google Cloud Platform

import pyspark
from pyspark import SparkContext, SparkConf
import elephas

conf = SparkConf().setAppName('App1').setMaster('local')
#SparkContext.getOrCreate().stop()
sc = SparkContext(conf=conf)

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:53 min
[INFO] Finished at: 2018-11-30T05:54:39+00:00
Traceback (most recent call last):
  File "/home/smasis/ml/./keras_pyspark_v1.py", line 23, in <module>
[INFO] Final Memory: 47M/1526M
[INFO] ------------------------------------------------------------------------
    sc = SparkContext(conf=conf)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 118, in _init_
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 180, in _do_init
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 282, in _initialize_context
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in _call_
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:238)
py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
py4j.GatewayConnection.run(GatewayConnection.java:238)
java.lang.Thread.run(Thread.java:748)
        at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2456)
        at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2452)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:2452)
        at org.apache.spark.SparkContext$.markPartiallyConstructed(SparkContext.scala:2541)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:84)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by maxpumperla** [comment]
you can't create multiple spark contexts, there must already be one running. note that in examples I create one to make them self contained.

**Comment by shailvshah** [comment]
How do I make sure I'm running just one? Because I followed the same code. 
Or do I need to stop the SparkContext?

**Comment by maxpumperla** [comment]
you just leave out the part where you create a new one...
