### ISSUE TITLE
_pickle.PicklingError: Could not serialize object: ValueError: substring not found

### ISSUE THREAD

**Issue by iamontheinet** [maxpumperla/elephas#151]
Hi!

I am trying out this example [https://github.com/maxpumperla/elephas/blob/master/examples/Spark_ML_Pipeline.ipynb](https://github.com/maxpumperla/elephas/blob/master/examples/Spark_ML_Pipeline.ipynb) and getting 
`_pickle.PicklingError: Could not serialize object: ValueError: substring not found` error 
when fitting the model at line -- _**fitted_pipeline = pipeline.fit(train_df) # Fit model to data**_

It appears that the exception is raised in `cloudpickle.dumps()` method of  **CloudPickleSerializer** class in **serializers.py**.

Here's the entire stack trace:

`
Traceback (most recent call last): File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/serializers.py", line 590, in dumps return cloudpickle.dumps(obj, 2) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/cloudpickle.py", line 863, in dumps cp.dump(obj) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/cloudpickle.py", line 260, in dump return Pickler.dump(self, obj) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 437, in dump self.save(obj) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 789, in save_tuple save(element) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/cloudpickle.py", line 406, in save_function self.save_function_tuple(obj) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/cloudpickle.py", line 549, in save_function_tuple save(state) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict self._batch_setitems(obj.items()) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems save(v) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 819, in save_list self._batch_appends(obj) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 846, in _batch_appends save(tmp[0]) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/cloudpickle.py", line 657, in save_instancemethod self.save_reduce(types.MethodType, (obj.__func__, obj.__self__), obj=obj) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 638, in save_reduce save(args) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 774, in save_tuple save(element) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 549, in save self.save_reduce(obj=obj, *rv) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce save(state) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict self._batch_setitems(obj.items()) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems save(v) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 819, in save_list self._batch_appends(obj) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 846, in _batch_appends save(tmp[0]) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 549, in save self.save_reduce(obj=obj, *rv) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce save(state) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict self._batch_setitems(obj.items()) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems save(v) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/Applications/anaconda3/lib/python3.7/pickle.py", line 819, in save_list self._batch_appends(obj) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 843, in _batch_appends save(x) File "/Applications/anaconda3/lib/python3.7/pickle.py", line 524, in save rv = reduce(self.proto) File "/Applications/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 827, in __reduce__ name=self._shared_name, File "/Applications/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 1154, in _shared_name return self.name[:self.name.index(":")] ValueError: substring not found During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 2381, in _call_proxy return_value = getattr(self.pool[obj_id], method)(*params) File "/var/folders/3x/4m7khlfx2ps64yb28d81jb340000gn/T/1576731199823-0/python_code_runner.py", line 55, in run exec(code, context) File "<string>", line 81, in <module> File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/ml/base.py", line 132, in fit return self._fit(dataset) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/ml/pipeline.py", line 109, in _fit model = stage.fit(dataset) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/ml/base.py", line 132, in fit return self._fit(dataset) File "/Applications/anaconda3/lib/python3.7/site-packages/elephas/ml_model.py", line 92, in _fit validation_split=self.get_validation_split()) File "/Applications/anaconda3/lib/python3.7/site-packages/elephas/spark_model.py", line 151, in fit self._fit(rdd, epochs, batch_size, verbose, validation_split) File "/Applications/anaconda3/lib/python3.7/site-packages/elephas/spark_model.py", line 188, in _fit gradients = rdd.mapPartitions(worker.train).collect() File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/rdd.py", line 816, in collect sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd()) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/rdd.py", line 2532, in _jrdd self._jrdd_deserializer, profiler) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/rdd.py", line 2434, in _wrap_function pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/rdd.py", line 2420, in _prepare_for_python_RDD pickled_command = ser.dumps(command) File "/Users/dash/spark-2.4.4-bin-without-hadoop/python/pyspark/serializers.py", line 600, in dumps raise pickle.PicklingError(msg) _pickle.PicklingError: Could not serialize object: ValueError: substring not found
`

Any pointers or advise will be much appreciated.

Thanks in advance!

Cheers,
Dash

**Comment by MunishaTripping** [comment]
Any solution to the above problem or any alternatives to distribute a keras model for regression . I am facing the same.

**Comment by markojurkovic** [comment]
Same issue here (running either natively in Windows or natively in Linux using WSL).

**Comment by michaelpetrolini** [comment]
It seems to be a conflict with keras/tensorflow. I've been able to solve this by downgrading Keras to version 2.2.4.

**Comment by apremgeorge** [comment]
Did that work with keras 2.2.4?

**Comment by michaelpetrolini** [comment]
Yes, I also had to downgrade Tensorflow to 1.14.0. here's a list of my working elephas environment:
absl-py==0.9.0
astor==0.8.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.1
certifi==2019.11.28
Click==7.0
cloudpickle==1.3.0
Cython==0.29.15
decorator==4.4.2
defusedxml==0.6.0
elephas==0.4.3
entrypoints==0.3
Flask==1.1.1
future==0.18.2
gast==0.3.3
google-pasta==0.1.8
grpcio==1.27.2
h5py==2.10.0
hyperas==0.4.1
hyperopt==0.2.3
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.0.0
jupyter-console==6.1.0
jupyter-core==4.6.3
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.2
notebook==6.0.3
numpy==1.18.1
pandas==1.0.1
pandocfilters==1.4.2
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.11.4
ptyprocess==0.6.0
py4j==0.10.7
Pygments==2.5.2
pymongo==3.9.0
pyrsistent==0.15.7
pyspark==2.4.5
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.3
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
scikit-learn==0.22.1
scipy==1.4.1
Send2Trash==1.5.0
six==1.14.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
tqdm==4.43.0
traitlets==4.3.3
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==3.1.0

**Comment by AntonOellerer** [comment]
Just fyi, with `tensorflow==1.15.3` and `keras==2.2.5` it should work aswell
