### ISSUE TITLE
TypeError: cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by amirtaherkhani** [maxpumperla/elephas#191]
I received this error after running "mnist_mlp_spark.py" example or any other example
os: macOS Big Sur 11.2.3
python : python3.8
tensorflow:2.4.1
elephas: 2.1.0
keras : 2.2.5
pyspark: 3.1.1

Traceback (most recent call last):
  File "/Users/amirtaherkhani/Desktop/big_recomender/deep learning/./train_spark.py", line 57, in <module>
    spark_model.fit(rdd, epochs=epochs, batch_size=batch_size, verbose=0, validation_split=0.1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elephas/spark_model.py", line 146, in fit
    self._fit(rdd, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elephas/spark_model.py", line 158, in _fit
    self.start_server()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elephas/spark_model.py", line 109, in start_server
    self.parameter_server.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elephas/parameter/server.py", line 83, in start
    self.server.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object

**Comment by danielenricocahall** [comment]
Hey try with the latest release (3.0.0) - I don't believe the previous version was tested on Tensorflow 2.4 in the previous release.
