### ISSUE TITLE
Py4JJavaError: An error occurred while calling o559._run.

### ISSUE THREAD

**Issue by afonsolenzi** [maxpumperla/elephas#201]
Hello i am trying run 2 notebooks in sequence at Databricks. Second Notebook will run with variables from the first Notebook

This is the command i am running:

`dbutils.notebook.run('Test_Variables', 0, {"DateToProcess": Var1,"OpCo": Var2}) `

Error message:

`Py4JJavaError: An error occurred while calling o559._run.
: com.databricks.WorkflowException: com.databricks.NotebookExecutionException: FAILED
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:96)
	at com.databricks.dbutils_v1.impl.NotebookUtilsImpl.run(NotebookUtilsImpl.scala:117)
	at com.databricks.dbutils_v1.impl.NotebookUtilsImpl._run(NotebookUtilsImpl.scala:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.databricks.NotebookExecutionException: FAILED
	at com.databricks.workflow.WorkflowDriver.run0(WorkflowDriver.scala:142)
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:91)
	... 13 more`

**Comment by afonsolenzi** [comment]
it was happening due to a aditional in the second notebook trying to convert the variable that was already converted in the first notebook. everything is working fine.
