### ISSUE TITLE
hyperparam_optimization.py:  Error when checking model target: expected activation_2 to have shape (None, 512) but got array with shape (60000, 10)

### ISSUE THREAD

**Issue by emmjaykay** [maxpumperla/elephas#36]
Hi,

A couple of weeks ago during late November I could get the example to work fine. However when I run the example hyperparam_optimization.py this week with most recent elephas I get the following

`  File "/usr/spark-2.0.2/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/usr/spark-2.0.2/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/spark-2.0.2/python/lib/pyspark.zip/pyspark/serializers.py", line 263, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/usr/local/lib/python2.7/dist-packages/elephas/hyperparam.py", line 86, in minimize
    trials=trials, full_model_string=self.model_string, rseed=rand_seed)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 90, in base_minimizer
    rstate=np.random.RandomState(rseed))
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "temp_model.py", line 98, in keras_fmin_fnct
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 652, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1038, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 967, in _standardize_user_data
    exception_prefix='model target')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 111, in standardize_input_data
    str(array.shape))
Exception: Error when checking model target: expected activation_2 to have shape (None, 512) but got array with shape (60000, 10)

        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
        at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
        at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:86)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/12/06 02:00:22 WARN scheduler.TaskSetManager: Lost task 3.0 in stage 1.0 (TID 11, localhost): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/spark-2.0.2/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/usr/spark-2.0.2/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/spark-2.0.2/python/lib/pyspark.zip/pyspark/serializers.py", line 263, in dump_stream
`

**Comment by maxpumperla** [comment]
Yes, as I said in the other ticket, I'll need to update this as soon as possible. Thanks for reporting it.

**Comment by maxpumperla** [comment]
the hyperparam example (and corresponding test) works again on master.
