### ISSUE TITLE
Serialization fails with error "TypeError: can't pickle ellipsis objects"

### ISSUE THREAD

**Issue by wmeints** [maxpumperla/elephas#59]
I tried to run Elephas, but it fails every time with the follow stack trace:

```
TypeError: can't pickle ellipsis objects
Traceback (most recent call last):
  File "/home/willem/projects/elephas/examples/./mnist_mlp_spark.py", line 66, in <module>
    spark_model.train(rdd, nb_epoch=nb_epoch, batch_size=batch_size, verbose=2, validation_split=0.1)
  File "/home/willem/.virtualenvs/elephas/local/lib/python2.7/site-packages/elephas/spark_model.py", line 197, in train
    self._train(rdd, nb_epoch, batch_size, verbose, validation_split, master_url)
  File "/home/willem/.virtualenvs/elephas/local/lib/python2.7/site-packages/elephas/spark_model.py", line 217, in _train
    rdd.mapPartitions(worker.train).collect()
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 809, in collect
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 2455, in _jrdd
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 2388, in _wrap_function
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 2374, in _prepare_for_python_RDD
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 460, in dumps
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 704, in dumps
  File "/home/willem/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 162, in dump
pickle.PicklingError: Could not serialize object: TypeError: can't pickle ellipsis objects
```

I think it has to do with how the Worker types and SparkModel are implemented. 
Can you shed some light on this?

**Comment by sflender** [comment]
I get the same error when installing elephas from source. No issue when installing elephas with pip  though.

**Comment by maxpumperla** [comment]
@sflender @wmeints can you check again on current master? Just did a big rewrite of elephas. I've never seen this issue before, but will leave it open for investigation.
