### ISSUE TITLE
Unable to run your example ml_mlp.py deserialize_keras_object

### ISSUE THREAD

**Issue by nagamanojk** [maxpumperla/elephas#61]
Hi, there seem to be lot of problem in executing ml_mlp.py.
After adding the following line in elephas/optimizers.py
Finally I got the error mentioned below.

import tensorflow as tf
import six
from keras import optimizers
from keras.optimizers import Adamax
from keras.optimizers import Nadam
from keras.optimizers import TFOptimizer

Traceback (most recent call last):
  File "/home/jayendran/elephas-master/examples/ml_mlp.py", line 80, in <module>
    fitted_pipeline = pipeline.fit(df)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 64, in fit
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/pipeline.py", line 113, in _fit
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 64, in fit
  File "/usr/local/lib/python2.7/dist-packages/elephas/ml_model.py", line 58, in _fit
    optimizer = get(self.get_optimizer_config())
  File "/usr/local/lib/python2.7/dist-packages/elephas/optimizers.py", line 290, in get
    return deserialize(identifier)
  File "/usr/local/lib/python2.7/dist-packages/elephas/optimizers.py", line 268, in deserialize
    printable_module_name='optimizer')
  File "/home/jayendran/.local/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/utils/generic_utils.py", line 142, in deserialize_keras_object
    raise ValueError('Improper config format: ' + str(config))
ValueError: Improper config format: {'epsilon': 1e-06, 'lr': 1.0, 'name': 'adadelta', 'rho': 0.95}

**Comment by maxpumperla** [comment]
runs on master, just did an overhaul

**Comment by mostafa-time** [comment]
This still seems to be an issue. I am getting the exact error as @nagamanojk . @maxpumperla would you please look into this? This issue seems to be the same thing: https://github.com/maxpumperla/elephas/issues/122

**Comment by maxpumperla** [comment]
@mostafa-time thanks for letting me know. I'll try to find time for this.

**Comment by mostafa-time** [comment]
Thank you @maxpumperla ! If you find it easier, I could take this on after you point me to the logic of what needs to be done.

**Comment by maxpumperla** [comment]
I think I fixed it already. Check out elephas 0.4.2

**Comment by mostafa-time** [comment]
Thanks @maxpumperla. I tried it and after few changes, the notebook example works (have a PR for it here https://github.com/maxpumperla/elephas/pull/138). However now I have a separate issue on my own data which later I found out later it seems to be elephas's problem with regression task: https://github.com/maxpumperla/elephas/issues/139
