### ISSUE TITLE
CNN Training HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Nicbyte** [maxpumperla/elephas#63]
Hi 

I'm testing out elephas trying to train a convolutional neural net.
I keep getting the error below. Any ideas?

17/10/17 11:22:44 INFO TaskSchedulerImpl: Adding task set 1.0 with 2 tasks
17/10/17 11:22:44 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 4, 10.1.11.11, executor 1, partition 0, NODE_LOCAL, 4901 bytes)
17/10/17 11:22:44 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 5, 10.1.11.12, executor 0, partition 1, NODE_LOCAL, 4901 bytes)
17/10/17 11:22:44 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.1.11.11:38413 (size: 6.8 KB, free: 366.3 MB)
17/10/17 11:22:44 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.1.11.12:34614 (size: 6.8 KB, free: 366.3 MB)
17/10/17 11:22:44 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 10.1.11.11:46710
17/10/17 11:22:44 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 10.1.11.12:51870
17/10/17 11:22:44 INFO MapOutputTrackerMaster: Size of output statuses for shuffle 0 is 161 bytes
10.1.11.12 - - [17/Oct/2017 11:22:51] "GET /parameters HTTP/1.1" 200 -
10.1.11.11 - - [17/Oct/2017 11:23:41] "GET /parameters HTTP/1.1" 200 -
17/10/17 11:33:47 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 10.1.11.10:43452 in memory (size: 3.4 KB, free: 366.3 MB)
17/10/17 11:33:47 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 10.1.11.12:34614 in memory (size: 3.4 KB, free: 366.3 MB)
17/10/17 11:33:47 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 10.1.11.11:38413 in memory (size: 3.4 KB, free: 366.3 MB)
10.1.11.12 - - [17/Oct/2017 11:36:49] "POST /update HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/elephas/spark_model.py", line 160, in update_parameters
  constraints = self.master_network.model.constraints
AttributeError: 'Model' object has no attribute 'constraints'
17/10/17 11:36:49 WARN TaskSetManager: Lost task 1.0 in stage 1.0 (TID 5, 10.1.11.12, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/opt/spark/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/opt/spark/spark-2.2.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/elephas/spark_model.py", line 309, in train
    weights_after_training = model.get_weights()
  File "/root/anaconda2/envs/py35/lib/python3.5/site-packages/elephas/spark_model.py", line 44, in put_deltas_to_server
    return urllib2.urlopen(request).read()
  File "/root/anaconda2/envs/py35/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/root/anaconda2/envs/py35/lib/python3.5/urllib/request.py", line 472, in open

Not sure if this is causing the ERROR 500... I can see the job going into Spark but then gets stuck at collect and fails eventually..

**Comment by rayjang** [comment]
I got the same problem. Anyone knows???

**Comment by rayjang** [comment]
I think I can solve it.
I will test mine. If I make it, i will let u know

**Comment by FelipeMarcelino** [comment]
I have the same problem here. How do i can fix this?

**Comment by agubelu** [comment]
I'm experiencing the same issue over here

**Comment by callmefregy** [comment]
i have the same problem too. Please help

**Comment by waniss** [comment]
also have the same issue, can you please help us ?

**Comment by maxpumperla** [comment]
hmm, guys. this is impossible for me to debug. I see from your stack trace that the GET request to retrieve parameters has a 200 response, so the server is up and running. but you do get a 500 at a later point. might be that the server crashes and doesn't recover. 

I've set the `use_reloader` option of Flask to `True` so the service recovers on failure. Apart from that there's not much more I can do in terms of fault-tolerance right now.

Maybe at some point we'll introduce a more stable parameter service to solve this (I have an idea coming up, but can't share yet).

**Comment by danielenricocahall** [comment]
Is this still an issue?

**Comment by danielenricocahall** [comment]
I'm going to close this for now - feel free to reopen if this issue persists.
