### ISSUE TITLE
py4j.Py4JException: Method __getnewargs__([]) does not exist

### ISSUE THREAD

**Issue by rayjang** [maxpumperla/elephas#69]
Why the problem happen???? 
File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 312, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling o17.__getnewargs__. Trace:
py4j.Py4JException: Method __getnewargs__([]) does not exist
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:335)
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:344)
        at py4j.Gateway.invoke(Gateway.java:252)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:748)

**Comment by JokerPW** [comment]
You left no code for us to look, still, as I'm getting the same error, I hope I can give you some directions while I work on my own code:
This problem happens when you try to iterate through a "pyspark.rdd.PipelinedRDD". As it extends the RDD, it should be iterable, but I had many problems in the near past trying to use it as one.
See if you can convert it to a DataFrame or an RDD (still not sure how nor which one) and replace the "list" you're using in the line of code you're getting this error.
Hope it helped.  =]
Cheers !

**Comment by maxpumperla** [comment]
@rayjang not sure I can do much for you here. I'm not seeing this error anywhere and I've just added a ton of new tests. Feel free to open another issue with _a lot_ more information.

**Comment by rajeevhcu** [comment]
File "/usr/local/lib/python3.6/dist-packages/pyspark/rdd.py", line 325, in map
    return self.mapPartitionsWithIndex(func, preservesPartitioning)
  File "/usr/local/lib/python3.6/dist-packages/pyspark/rdd.py", line 365, in mapPartitionsWithIndex
    return PipelinedRDD(self, f, preservesPartitioning)
  File "/usr/local/lib/python3.6/dist-packages/pyspark/rdd.py", line 2514, in __init__
    self.is_barrier = prev._is_barrier() or isFromBarrier
  File "/usr/local/lib/python3.6/dist-packages/pyspark/rdd.py", line 2414, in _is_barrier
    return self._jrdd.rdd().isBarrier()
  File "/home/rajeev/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/rajeev/.local/lib/python3.6/site-packages/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling o22.isBarrier. Trace:
py4j.Py4JException: Method isBarrier([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rajeevhcu** [comment]
I am not getting why this error coming
