### ISSUE TITLE
Issue with mnist_mlp_spark.py example

### ISSUE THREAD

**Issue by sflender** [maxpumperla/elephas#73]
Hi, I'm running into the error message below when running the mnist_mlp_spark.py example. I'm using Python 2.7, Keras 0.3.3, Spark 2.2.0. Any idea what is going wrong?

17/11/28 23:38:20 ERROR Executor: Exception in task 1.0 in stage 1.0 (TID 9)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/Cellar/apache-spark/2.2.0/libexec/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/usr/local/Cellar/apache-spark/2.2.0/libexec/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/local/Cellar/apache-spark/2.2.0/libexec/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/Users/samuelflender/anaconda/envs/my_elephas_env/lib/python2.7/site-packages/elephas/spark_model.py", line 265, in train
    model.fit(x_train, y_train, show_accuracy=True, **self.train_config)
  File "/Users/samuelflender/anaconda/envs/my_elephas_env/lib/python2.7/site-packages/keras/models.py", line 639, in fit
    val_f = self._test_with_acc
AttributeError: 'Sequential' object has no attribute '_test_with_acc'

**Comment by sflender** [comment]
Ok I found the issue, there is a compile model command missing in the code. Call model.compile(loss='categorical_crossentropy', optimizer='adam') before defining spark_model.
