### ISSUE TITLE
Problem with running mnist_mlp_spark.py example

### ISSUE THREAD

**Issue by menon92** [maxpumperla/elephas#74]
I am getting this error. 
```
File "/home/semanticslab3/development/spark/spark-2.2.1-bin-hadoop2.7/python/pyspark/cloudpickle.py", line 162, in dump
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not serialize object: TypeError: can't pickle _thread.lock objects
```

**Comment by gzgywh** [comment]
I got the same problem,how to solve it?

**Comment by maxpumperla** [comment]
@gzgywh why do you open a new issue with exactly the same content? I'm closing this one in favour of  #82 then.

Guys, could you please give me a little more info on what you do and how you do it?

**Comment by gzgywh** [comment]
I run mnist_mlp_spark.py in example on spark yarn

TypeError: can't pickle _thread.lock objects
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/gzgywh/Desktop/mnist_mlp_spark.py", line 67, in 
spark_model.train(rdd, nb_epoch=nb_epoch, batch_size=batch_size, verbose=2, validation_split=0.1)
File "/home/gzgywh/Desktop/elephas/dist/elephas-0.3-py3.6.egg/elephas/spark_model.py", line 198, in train
File "/home/gzgywh/Desktop/elephas/dist/elephas-0.3-py3.6.egg/elephas/spark_model.py", line 223, in _train
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 809, in collect
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2455, in _jrdd
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2388, in _wrap_function
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 2374, in _prepare_for_python_RDD
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 460, in dumps
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 704, in dumps
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 162, in dump
_pickle.PicklingError: Could not serialize object: TypeError: can't pickle _thread.lock object
