### ISSUE TITLE
How to set up elephas on spark workers with --archives

### ISSUE THREAD

**Issue by ivan-bilan** [maxpumperla/elephas#80]
When running the basic example from the doc:

> from elephas.utils.rdd_utils import to_simple_rdd
rdd = to_simple_rdd(sc, x_train, y_train)
from elephas.spark_model import SparkModel
from elephas import optimizers as elephas_optimizers
sgd = elephas_optimizers.SGD()
spark_model = SparkModel(sc, model, optimizer=sgd, frequency='epoch', mode='asynchronous', num_workers=2)
spark_model.train(rdd, nb_epoch=epochs, batch_size=batch_size, verbose=1, validation_split=0.1)

I get the following error:
**"ImportError: No module named elephas.spark_model"**
 I use PySpark 2.1 and Keras 2. Any suggestions?

```Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 5.0 failed 4 times, most recent failure: Lost task 1.3 in stage 5.0 (TID 58, xxxx, executor 8): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/xx/xx/hadoop/yarn/local/usercache/xx/appcache/application_1512662857247_19188/container_151xxx2857247_19188_01_000009/pyspark.zip/pyspark/worker.py", line 163, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/xx/xx/hadoop/yarn/local/usercache/xx/appcache/application_1512662857247_19188/container_151xxx2857247_19188_01_000009/pyspark.zip/pyspark/worker.py", line 54, in read_command
    command = serializer._read_with_length(file)
  File /yarn/local/usercache/xx/appcache/application_1512xx57247_19x8/container_1512xxx857247_19188_01_000009/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/yarn//local/usercache/xx/appcache/application_1512xx57247_19x8/container_1512xxx857247_19188_01_000009/pyspark.zip/pyspark/serializers.py", line 454, in loads
    return pickle.loads(obj)
ImportError: No module named elephas.spark_model

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by ivan-bilan** [comment]
Can anyone give me any pointers?
Basically, I can do ```import elephas``` without any errors, but when I import _SparkModel_, I get the error. I've installed elephas using _pip2 install git+https://github.com/maxpumperla/elephas_

**Comment by maxpumperla** [comment]
@ivan-bilan it seems this happens when deserialising the model on workers (`pickle.loads(...)`) for training. are you sure you installed elephas there as well? It seems your spark master knows elephas.

**Comment by ivan-bilan** [comment]
@maxpumperla I rely on uploading the zip file of the virtual environment and call it within the script:
    
    virtualenv spark_venv --relocatable
    cd spark_venv 
    zip -qr ../spark_venv.zip *
    
    PYSPARK_DRIVER_PYTHON=`which python` spark-submit --driver-memory 1G --py-files spark_venv.zip filename.py

Then in the file I do:
    sc.addPyFile("spark_venv.zip")

I guess the venv is not read by the workers. I may be missing some step here.

**Comment by maxpumperla** [comment]
yeah, production systems are always a little messy. in the end I can only guess what's going on. keep me posted in case I can help somehow.

**Comment by ivan-bilan** [comment]
I found the solution on how to properly distribute the virutalenv to the workers as well:

```
virtualenv venv --relocatable
cd venv 
zip -qr ../venv.zip *

PYSPARK_PYTHON=./SP/bin/python spark-submit --master yarn --deploy-mode cluster --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=./SP/bin/python --driver-memory 4G --archives venv.zip#SP filename.py
```

This is mainly based on the following blog post: https://henning.kropponline.de/2016/09/17/running-pyspark-with-virtualenv/

**Comment by maxpumperla** [comment]
cool, thanks for your feedback. I've changed the name of the issue so people can find this. at some point I want to write up how to use elephas from scratch on AWS  or GCE etc., this might be very helpful.
