### ISSUE TITLE
Exception: It appears that you are attempting to reference SparkContext from a broadcast variable, action, or transformation. SparkContext can only be used on the driver, not in code that it run on workers. For more information, see SPARK-5063.

### ISSUE THREAD

**Issue by mohaimenz** [maxpumperla/elephas#88]
> Could you please help me? I am giving my model and the error that I am seeing here.
```
model.compile(loss=lossFunc, optimizer=gradDiscent, metrics=['accuracy']);
##############################START: DISTRIBUTED MODEL################
from pyspark import SparkContext, SparkConf
#Create spark context
conf = SparkConf().setAppName('NSL-KDD-DISTRIBUTED').setMaster('local[8]');
sc = SparkContext(conf=conf);

from elephas.utils.rdd_utils import to_simple_rdd
#Build RDD (Resilient Distributed Dataset) from numpy features and labels
rdd = to_simple_rdd(sc, trainX, trainY);

from elephas.spark_model import SparkModel
from elephas import optimizers as elephas_optimizers
#Initialize SparkModel from Keras model and Spark Context
elphOptimizer = elephas_optimizers.Adagrad();
sparkModel = SparkModel(sc, model, optimizer=elphOptimizer, frequency='epoch', model='asynchronous', num_workers=1);
#Train Spark Model
sparkModel.train(rdd, nb_epoch=epochs, batch_size=batchSize, verbose=2);

#Evaluate Spark Model
score = sparkModel.master_network.evaluate(testX, testY, verbose=2);
print(score);
```
####################ERROR########################
Traceback (most recent call last):
  File "C:\PythonWorks\mine\dm-dist.py", line 230, in <module>
    sparkModel.train(rdd, nb_epoch=epochs, batch_size=batchSize, verbose=2);
  File "C:\Miniconda3\lib\site-packages\elephas\spark_model.py", line 194, in train
    self._train(rdd, nb_epoch, batch_size, verbose, validation_split, master_url)
  File "C:\Miniconda3\lib\site-packages\elephas\spark_model.py", line 205, in _train
    self.start_server()
  File "C:\Miniconda3\lib\site-packages\elephas\spark_model.py", line 125, in start_server
    self.server.start()
  File "C:\Miniconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Miniconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Miniconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Miniconda3\lib\site-packages\pyspark\context.py", line 306, in __getnewargs__
    "It appears that you are attempting to reference SparkContext from a broadcast "
Exception: It appears that you are attempting to reference SparkContext from a broadcast variable, action, or transformation. SparkContext can only be used on the driver, not in code that it run on workers. For more information, see SPARK-5063.

**Comment by mohaimenz** [comment]
@maxpumperla could you please let us know if there is a plan to fix this? If yes then could you please give us a rough idea about the time?

**Comment by maxpumperla** [comment]
@mohaimenz look, I'm sorry you're frustrated about this, but I don't give any time frames here. Also, duplicating tickets doesn't speed up anything.

I'm trying to figure this out, believe me. There's one place we use broadcasting and that's in `synchronous` mode, which you aren't using.  It's here:

```
            init = self.master_network.get_weights()
            parameters = self.spark_context.broadcast(init)
            worker = SparkWorker(
                yaml, parameters, train_config, 
                self.master_optimizer, self.master_loss, self.master_metrics, self.custom_objects
            )
```

if you feel adventurous, change this to 

```
            init = self.master_network.get_weights()
            worker = SparkWorker(
                yaml, init, train_config, 
                self.master_optimizer, self.master_loss, self.master_metrics, self.custom_objects
            )
```

and tell me what happens. That might actually help out, you know :)

**Comment by mohaimenz** [comment]
@maxpumperla fair enough from you. I choose to use this library instead of dist-keras as I love the way it has been done. Furthermore, I am using theano back end. I will try with it and let you know how it goes...

**Comment by maxpumperla** [comment]
@mohaimenz thanks. yeah, I'm not 100% happy with dist-keras for the simple reason that it _obviously_ started as an elephas fork without ever crediting it (until I forced the guy to do it). 

This is how open source dies... instead of trying to grab GitHub fame (useless stars) and being selfish, just try to help out. If Joeri had just put his time into patching elephas and become maintainer, which I would have offered, instead of stealing it, we'd have a better product now, not 2 mediocre ones that compete. Alright, that's my rant, haha. :D

**Comment by mohaimenz** [comment]
@maxpumperla Yeah! I saw the conversation. Finally, he put elephas in reference. I looked at his initial commits and found that they he basically started on top of elephas. I hope elephas will have great future and will be integrated with keras. According to Francois, it is being considered to have features like this.https://www.quora.com/What-is-the-state-of-distributed-learning-multi-GPU-and-across-multiple-hosts-in-Keras-and-what-are-the-future-plans

**Comment by mohaimenz** [comment]
@maxpumperla I updated spark_model.py and used tried using it as a custom class for my app. Sill the same error. I will continue working on it and let you know if I find any luck

**Comment by mohaimenz** [comment]
@maxpumperla just an update. It seems that somehow this error is connected to this error
`ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:64249)`
It seems that it is trying to connect to dynamic port every time and throwing this error when creating SpartContext. I will update you more if I can come out from this issue.

**Comment by mohaimenz** [comment]
@maxpumperla Just for an update. There was no luck to fix. If I had time, I would have put an in depth look but I am really in a crunch of moment. I need to get other stuffs done for my PhD. I probably need to look at other alternatives for do the distributed training of my DNN model. I would love to hear about the fix in near future.

**Comment by maxpumperla** [comment]
@mohaimenz thanks for your update, good to hear you're still trying. and apologies for the lack of time on my side.

**Comment by mohaimenz** [comment]
Thanks a lot for your reply. By the way, may I have your suggestion regarding my last question?

**Comment by mohaimenz** [comment]
@maxpumperla I was debugging SparkModel class and found that the error is happening in this line start_server() method when it is trying to start the server (in this line: self.server.start()). As it is saying the exactly the same error (the title of this thread), I made start_service() method static so that it can be used globally regardless of the class instance to make sure that it is not locked by another instance. It does not help. The original error went away but a new error:
py4j.protocol.Py4JJavaError was unhandled by user code
Message: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.io.IOException: Cannot run program "python": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:133)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:76)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:86)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:64)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 18 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1602)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1590)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1589)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1589)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1823)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1772)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1761)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:939)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:938)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:162)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Cannot run program "python": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:133)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:76)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:86)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:64)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 18 more

**Comment by maxpumperla** [comment]
@mohaimenz hmm, that looks suspiciously like Spark can't find your Python installation... is `pyspark` on your `PATH`? how do you start the process (which command do you use to run in CLI)?

btw, have you tried using `synchronous` mode?

**Comment by mohaimenz** [comment]
@maxpumperla: I am using visual studio for debugging. It says that spark cant find python, so it falls back to the default python istallation which is fine. I also use conda prompt and I do not see the python istallation issue. Rather, I directly see that it is failing. BTW I am running it in windows.

Yes, I tried to run synchronous mode (which I should not use because I want to achive distributed model training) and I see the same issue. I am sure I am missing something. I really need to be able to run it. My experiment is entire done using theano and that is why I am still trying ELEPHAS as other APIs use tensorflow. If I can run it and if you want then I can add the fix in elephas project. I am just new in this deep learning and keras stuff

**Comment by mohaimenz** [comment]
@maxpumperla : This is what my code looks like.
```
model = Sequential();
model.add(Dropout(0.2, input_shape=(122,)));
model.add(Dense(150, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)));
model.add(Dropout(0.5));
model.add(Dense(120, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)));
model.add(Dropout(0.5));
model.add(Dense(50, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)));
model.add(Dropout(0.5));
model.add(Dense(2, kernel_initializer='normal', activation='sigmoid'));

sgd = SGD(lr=0.1, momentum=0.9, decay=1e-6, nesterov=True);
model.compile(loss='mean_squared_error', optimizer=sgd, metrics=['accuracy']);

######################START: DISTRIBUTED MODEL##################################
from pyspark import SparkContext, SparkConf
#Create spark context
conf = SparkConf().setAppName('MY-DISTRIBUTED').setMaster('local[4]');
sc = SparkContext(conf=conf);

from elephas.utils.rdd_utils import to_simple_rdd
#Build RDD (Resilient Distributed Dataset) from trainX and trainY which are numpy array variables
rdd = to_simple_rdd(sc, trainX, trainY);

from elephas.spark_model import SparkModel
#from m_spark_model import SparkModel
from elephas import optimizers as elephas_optimizers
#Initialize SparkModel from Keras model and Spark Context
elphOptimizer = elephas_optimizers.Adagrad();
sparkModel = SparkModel(sc, model, optimizer=elphOptimizer, frequency='epoch', model='asynchronous', num_workers=1);
#Train Spark Model
sparkModel.train(rdd, nb_epoch=epochs, batch_size=batchSize, verbose=2);
#Evaluate Spark Model
score = sparkModel.master_network.evaluate(testX, testY, verbose=2);
###############END: DISTRIBUTED MODEL##################################
```

**Comment by mohaimenz** [comment]
@maxpumperla it seems that we have to follow https://docs.python.org/2/library/multiprocessing.html#the-process-class which basically fixes broadcasting issue. I am working on it. Now I am seeing the following error:
```
Using Theano backend.
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '1924' (I am process '8816')
2018-07-12 14:35:59 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
<SparkContext master=local[2] appName=MY-DISTRIBUTED>
[Stage 0:>                                                          (0 + 2) / 2]Using Theano backend.
[Stage 1:>                                                          (0 + 2) / 2]Using Theano backend.
2018-07-12 14:36:05 ERROR Executor:91 - Exception in task 0.0 in stage 1.0 (TID 2)
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at java.io.DataInputStream.readInt(Unknown Source)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:428)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:421)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:252)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:939)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:939)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
       .
       .
       .
```

**Comment by mohaimenz** [comment]
@maxpumperla Hi Max, I would like to close this issue because the initial error (the title of the issue) has been solved and I mentioned it in the last comment. Before that, could you please tell me if you had a chance to see if elephas works in Windows? I am using windows and it is it not working. I even can't run an example on windows. I would be glad to see your response about this question.

**Comment by mohaimenz** [comment]
@maxpumperla Hi Max, I am closing this issue. I have found that ELEPHAS does not work in windows. I have ran it in Linux and it is working. However, only frequency='epochs'. Frequency type 'batch' does not work because you are using Slice_X there which does not exist in KEras anymore. I will open a new issue for that.
