### ISSUE TITLE
py4j.protocol.Py4JJavaError and Connection refused in using example code

### ISSUE THREAD

**Issue by wuhang100** [maxpumperla/elephas#99]
@maxpumperla Hi, I am new to spark and I would like to apply your amazing code in my project, but it seems like I meet some problems in executing the `mnist_mlp_spark.py` example. The problems come in line `spark_model.fit(rdd, epochs=epochs, batch_size=batch_size, verbose=2, validation_split=0.1)`
1.
<pre>Traceback (most recent call last):
  File &quot;/home/wuhang/pythonwork/ipynotebook/model1.py&quot;, line 23, in &lt;module&gt;
    sc = SparkContext(conf=conf)
  File &quot;/usr/local/spark/python/lib/pyspark.zip/pyspark/context.py&quot;, line 118, in __init__
  File &quot;/usr/local/spark/python/lib/pyspark.zip/pyspark/context.py&quot;, line 180, in _do_init
  File &quot;/usr/local/spark/python/lib/pyspark.zip/pyspark/context.py&quot;, line 282, in _initialize_context
  File &quot;/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py&quot;, line 1525, in __call__
  File &quot;/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py&quot;, line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.api.java.JavaSparkContext.&lt;init&gt;(JavaSparkContext.scala:58)
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:238)
py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
py4j.GatewayConnection.run(GatewayConnection.java:238)
java.lang.Thread.run(Thread.java:748)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2456)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2452)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:2452)
	at org.apache.spark.SparkContext$.markPartiallyConstructed(SparkContext.scala:2541)
	at org.apache.spark.SparkContext.&lt;init&gt;(SparkContext.scala:84)
	at org.apache.spark.api.java.JavaSparkContext.&lt;init&gt;(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
</pre>

2. the `<urlopen error [Errno 111] Connection refused>` and it comes out several times
<pre>18/09/13 13:47:36 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File &quot;/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py&quot;, line 230, in main
    process()
  File &quot;/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py&quot;, line 225, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File &quot;/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py&quot;, line 372, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File &quot;/home/wuhang/anaconda2/lib/python2.7/site-packages/elephas/worker.py&quot;, line 98, in train
    weights_before_training = self.client.get_parameters()
  File &quot;/home/wuhang/anaconda2/lib/python2.7/site-packages/elephas/parameter/client.py&quot;, line 55, in get_parameters
    pickled_weights = urllib2.urlopen(request).read()
  File &quot;/home/wuhang/anaconda2/lib/python2.7/urllib2.py&quot;, line 154, in urlopen
    return opener.open(url, data, timeout)
  File &quot;/home/wuhang/anaconda2/lib/python2.7/urllib2.py&quot;, line 429, in open
    response = self._open(req, data)
  File &quot;/home/wuhang/anaconda2/lib/python2.7/urllib2.py&quot;, line 447, in _open
    &apos;_open&apos;, req)
  File &quot;/home/wuhang/anaconda2/lib/python2.7/urllib2.py&quot;, line 407, in _call_chain
    result = func(*args)
  File &quot;/home/wuhang/anaconda2/lib/python2.7/urllib2.py&quot;, line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File &quot;/home/wuhang/anaconda2/lib/python2.7/urllib2.py&quot;, line 1198, in do_open
    raise URLError(err)
URLError: &lt;urlopen error [Errno 111] Connection refused&gt;

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:298)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:438)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:421)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:252)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:939)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:939)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre>

I use the spark local mode and directly submit the py job `spark-submit --driver-memory 1G file:/home/wuhang/pythonwork/ipynotebook/model1.py` without changing anything in the code, could you please tell me whether there is any wrong in my operation?

**Comment by danielenricocahall** [comment]
Is this still an issue?

**Comment by danielenricocahall** [comment]
Closing this for now.
